server:
  port: 8080

spring:
  application:
    name: hikvision

# 配置海康威视 sdk 位置
hik:
  path: classpath:sdk/win
  # 直播流保活时间(分钟)
  keepalive: 5
  # Nginx 推送地址
  pushIp: 127.0.0.1
  # Nginx 推送端口
  pushPort: 1935